trigger:
- master
- release/*

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'


# Build source, tests and run tests with coverage
- script: |
    dotnet test ./UrbanNoise.Importer.Components.Tests/UrbanNoise.Importer.Components.Tests.csproj -c Debug --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  displayName: 'Build source, tests and run tests with coverage'

# Upload coverage to codecov.io
- script: |
    %USERPROFILE%\.nuget\packages\codecov\1.9.0\tools\codecov.exe -f "./UrbanNoise.Importer.Components.Tests/coverage.opencover.xml" -t $(CODECOV_TOKEN)
  displayName: Upload coverage to codecov.io

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  condition: ne(variables['system.pullrequest.isfork'], true)
  inputs:
    command: publish
    publishWebProjects: false
    arguments: '-o "$(build.artifactstagingdirectory)/Publish" --configuration $(BuildConfiguration) --no-build --no-restore'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  condition: ne(variables['system.pullrequest.isfork'], true)
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/Publish'
    ArtifactName: 'Function'




