trigger:
- master
- release/*

variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BuildConfiguration: Release
  BuildPlatform: Any CPU

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --no-build --no-restore'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  condition: ne(variables['system.pullrequest.isfork'], true)
  inputs:
    command: publish
    publishWebProjects: false
    arguments: '-o "$(build.artifactstagingdirectory)/Publish" --configuration $(BuildConfiguration) --no-build --no-restore'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  condition: ne(variables['system.pullrequest.isfork'], true)
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)/Publish'
    ArtifactName: 'Function'




